# Generated by Django 4.1.3 on 2022-11-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_inventory_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='inventory_quality',
        ),
        migrations.AddField(
            model_name='products',
            name='inventory_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
