# Generated by Django 4.1.3 on 2022-11-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
